# Form implementation generated from reading ui file 'test_qtable.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

# thu vien hien thi tren qtable 
from PyQt6.QtWidgets import QTableWidgetItem

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.tblDanhSach = QtWidgets.QTableWidget(parent=Form)
        self.tblDanhSach.setGeometry(QtCore.QRect(70, 50, 256, 192))
        self.tblDanhSach.setObjectName("tblDanhSach")
        self.tblDanhSach.setColumnCount(0)
        self.tblDanhSach.setRowCount(0)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        # Ham hien thi du lieu khi cua so duoc hien thi
        self.form_load()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))

    # Xay dung ham 
    def form_load(self):
        # du lieu mau 
        products = [
            {"name": "Samsung 10", "price": 1000}, 
            {"name": "Samsung 11", "price": 2000}, 
            {"name": "Samsung 12", "price": 3000}, 
        ]

        # thiet lap so hang
        self.tblDanhSach.setRowCount(len(products))

        # thiet lap so cot
        self.tblDanhSach.setColumnCount(2)

        # thiet lap nhan hien thi tren giao dien 
        self.tblDanhSach.setHorizontalHeaderLabels(["Tên", "Giá"])

        # thiet lap do rong cua tung cot 
        self.tblDanhSach.setColumnWidth(0, 120)
        self.tblDanhSach.setColumnWidth(1, 60)

        # hien thi du lieu len tren giao dien 
        i = 0
        for pro in products:
            self.tblDanhSach.setItem(i, 0, QTableWidgetItem(str(pro["name"])))
            self.tblDanhSach.setItem(i, 1, QTableWidgetItem(str(pro["price"])))
            i += 1

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
