# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

# thu vien thong bao 
from PyQt6.QtWidgets import QMessageBox

# thu vien json 
import json

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(385, 276)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 30, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 91, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.txtUsername = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtUsername.setGeometry(QtCore.QRect(170, 70, 161, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtUsername.setFont(font)
        self.txtUsername.setObjectName("txtUsername")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 130, 91, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.txtPassword = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtPassword.setGeometry(QtCore.QRect(170, 130, 161, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtPassword.setFont(font)
        self.txtPassword.setObjectName("txtPassword")
        self.btnLogin = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnLogin.setGeometry(QtCore.QRect(140, 190, 91, 31))
        self.btnLogin.setObjectName("btnLogin")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 385, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # Ket noi voi ham xu ly nghiep vu
        self.btnLogin.clicked.connect(self.xu_ly_dang_nhap)
    

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "LOGIN FORM"))
        self.label_2.setText(_translate("MainWindow", "Username:"))
        self.label_3.setText(_translate("MainWindow", "Password:"))
        self.btnLogin.setText(_translate("MainWindow", "L O G I N"))

    # Ham xu ly dang nhap
    def xu_ly_dang_nhap(self):
        # lay du lieu tu man hinh 
        username = self.txtUsername.text().strip() # Ham strip để cắt, loại bỏ khoảng trắng dư thừa ở đầu và đuôi
        password = self.txtPassword.text().strip()

        # kiem tra rong 
        if username == "":
            self.thong_bao("Thông báo lỗi", "Username không được để trống!")
            return
        elif password == "":
            self.thong_bao("Thông báo lỗi", "Password không được để trống!")
            return
    
        # mo tep de doc du lieu
        with open("account.json", "r") as file:
            data_account = json.load(file)
        
        # kiem tra tai khoan co trong file json
        for item in data_account["accounts"]:
            if item["username"] == username and item["password"] == password:
                self.thong_bao("Thông báo", "Bạn đã đăng nhập thành công!")
                return
        # neu duyet het ma khong tim thay
            else:
                self.thong_bao("Thông báo lỗi", "Tài khoản của bạn chưa được đăng ký. Chuyển sang màn hình đăng ký!")
                return

    # Ham thong bao cho nguoi dung 
    def thong_bao(self, set_title, set_text):
        msg=QMessageBox()
        msg.setIcon(QMessageBox.Icon.Information)
        msg.setWindowTitle(set_title)
        msg.setText(set_text)
        msg.exec()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
