# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(317, 467)
        # Lệnh tắt phóng to màn hình window
        MainWindow.setWindowFlag(QtCore.Qt.WindowType.FramelessWindowHint)
        MainWindow.setAttribute(QtCore.Qt.WidgetAttribute.WA_TranslucentBackground)
        MainWindow.setStyleSheet("QPushButton#btnLogin{\n"
"    background-color: rgba(79, 86, 146, 1);\n"
"    color: rgba(237, 237, 237, 0.9); \n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton#btnLogin:pressed{\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    backgroud-color: rgba(18, 101, 188, 0.7);\n"
"}\n"
"\n"
"QPushButton#btnLogin:hover{\n"
"    background-color: rgba(79, 86, 146, 0.8);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 290, 410))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setGeometry(QtCore.QRect(0, 0, 290, 410))
        self.label.setStyleSheet("background-color: rgba(6, 14, 91, 0.9);\n"
"border-radius: 15px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.txtUsername = QtWidgets.QLineEdit(parent=self.widget)
        self.txtUsername.setGeometry(QtCore.QRect(20, 210, 250, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtUsername.setFont(font)
        self.txtUsername.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border-radius: 1px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgba(255,255,255,1);\n"
"color: rgb(255,255,255);\n"
"padding-bottom: 7px;\n"
"")
        self.txtUsername.setObjectName("txtUsername")
        self.txtPassword = QtWidgets.QLineEdit(parent=self.widget)
        self.txtPassword.setGeometry(QtCore.QRect(20, 250, 250, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtPassword.setFont(font)
        self.txtPassword.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border-radius: 1px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgba(255,255,255,1);\n"
"color: rgb(255,255,255);\n"
"padding-bottom: 7px;\n"
"")
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtPassword.setObjectName("txtPassword")
        self.btnLogin = QtWidgets.QPushButton(parent=self.widget)
        self.btnLogin.setGeometry(QtCore.QRect(20, 310, 250, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnLogin.setFont(font)
        self.btnLogin.setObjectName("btnLogin")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setGeometry(QtCore.QRect(60, 30, 180, 150))
        font = QtGui.QFont()
        font.setFamily("dripicons-v2")
        font.setPointSize(70)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgba(80, 93, 206, 0.8);")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setGeometry(QtCore.QRect(20, 370, 250, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255,255,255);")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 317, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.txtUsername.setPlaceholderText(_translate("MainWindow", "   Username"))
        self.txtPassword.setPlaceholderText(_translate("MainWindow", "   Password"))
        self.btnLogin.setText(_translate("MainWindow", "L o g i n"))
        self.label_2.setText(_translate("MainWindow", ""))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p>Forget your Username or Password?</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
