# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
# import thu vien thong bao
from PyQt6.QtWidgets import QMessageBox
# import thu vien regex

import re


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(336, 319)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 10, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 71, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.txtEmail = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtEmail.setGeometry(QtCore.QRect(140, 50, 171, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.txtEmail.setFont(font)
        self.txtEmail.setObjectName("txtEmail")
        self.txtPassword = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtPassword.setGeometry(QtCore.QRect(140, 110, 171, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.txtPassword.setFont(font)
        self.txtPassword.setObjectName("txtPassword")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 71, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.txtRePassword = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtRePassword.setGeometry(QtCore.QRect(140, 170, 171, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.txtRePassword.setFont(font)
        self.txtRePassword.setObjectName("txtRePassword")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 170, 111, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.btnRegister = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnRegister.setGeometry(QtCore.QRect(120, 230, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnRegister.setFont(font)
        self.btnRegister.setObjectName("btnRegister")

        # Ket noi den ham xu ly 
        self.btnRegister.clicked.connect(self.xu_ly_dang_ky)

        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 336, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "REGISTER FORM"))
        self.label_2.setText(_translate("MainWindow", "Email:"))
        self.label_3.setText(_translate("MainWindow", "Password:"))
        self.label_4.setText(_translate("MainWindow", "Re-password:"))
        self.btnRegister.setText(_translate("MainWindow", "REGISTER"))

    # Ham Kiem tra tinh hop le cua email 
    def kiem_tra_email(self, email):
        # Cách 1: Kiểm tra địa chỉ Email hợp lệ bằng biểu thức chính quy
        regex = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,7}\b'
        if(re.fullmatch(regex, email)):
            return True
        else:
            return False
        
    # Ham kiem tra tinh hop le cua password 
    def kiem_tra_password(self, password):
        reg = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!#%*?&]{6,20}$"
        pat = re.compile(reg)
        mat = re.search(pat, password)
        if mat:
            return True
        else:
            return False

    # Tao Ham xu_ly_da_ky
    def xu_ly_dang_ky(self):
        # Lay du lieu tu form 
        email = self.txtEmail.text().strip()
        password = self.txtPassword.text().strip()
        repassword = self.txtRePassword.text().strip()
    # Ham strip() loại bỏ đi khoảng trang ở đầu và cuối dữ liệu 

        # Kiem tra rong 
        if email == "":
            self.thong_bao_loi("Thông báo lỗi", "Email không được để trống!")
            return
        elif password == "":
            self.thong_bao_loi("Thông báo lỗi", "Password không được để trống!")
            return
        elif repassword == "":
            self.thong_bao_loi("Thông báo lỗi", "Re-password không được để trống!")
            return
        

         # Kiem tra tinh hop le cua email
        if self.kiem_tra_email(email) == False:
            self.thong_bao_loi("Thông báo lỗi", "Email không hợp lệ!")
            return
        
        # Kiem tra tinh hop le cua password
        if self.kiem_tra_password(password) == False:
            self.thong_bao_loi("Thông báo lỗi", "Password không hợp lệ!")
            return

        # Kiem tra re-password trung khop voi password 
        if repassword != password:
            self.thong_bao_loi("Thông báo lỗi", "Re-password không trùng khớp với nhau!")
            return

    # Ham hien thi thong bao erorr
    def thong_bao_loi(self, set_title, set_text):
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Icon.Information)
        msg.setWindowTitle(set_title)
        msg.setText(set_text)
        msg.setStandardButtons(QMessageBox.StandardButton.Ok)
        msg.exec()

        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
