# Form implementation generated from reading ui file 'window_2.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Second_window(object):
    def setupUi(self, Second_window):
        Second_window.setObjectName("Second_window")
        Second_window.resize(320, 166)
        self.centralwidget = QtWidgets.QWidget(parent=Second_window)
        self.centralwidget.setObjectName("centralwidget")
        self.Second_window_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Second_window_2.setGeometry(QtCore.QRect(40, 30, 251, 71))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.Second_window_2.setFont(font)
        self.Second_window_2.setObjectName("Second_window_2")
        Second_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Second_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 320, 18))
        self.menubar.setObjectName("menubar")
        Second_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Second_window)
        self.statusbar.setObjectName("statusbar")
        Second_window.setStatusBar(self.statusbar)

        self.retranslateUi(Second_window)
        QtCore.QMetaObject.connectSlotsByName(Second_window)

    def retranslateUi(self, Second_window):
        _translate = QtCore.QCoreApplication.translate
        Second_window.setWindowTitle(_translate("Second_window", "MainWindow"))
        self.Second_window_2.setText(_translate("Second_window", "Đây là cửa sổ thứ 2 "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Second_window = QtWidgets.QMainWindow()
    ui = Ui_Second_window()
    ui.setupUi(Second_window)
    Second_window.show()
    sys.exit(app.exec())
